name: Code Verification and Tests

#Trigger the workflow
on:
  push:
    branches: [ "main" ]  # Trigger on push to the main branch
  pull_request:
    branches: [ "main" ]  # Trigger on pull requests to the main branch
  workflow_dispatch:      # Allow manual trigger (in the Actions tab)

#Define the jobs in this workflow
jobs:
  verify-and-test:
    name: Verify Code and Run Tests
    runs-on: ubuntu-latest  # Use the latest Ubuntu runner

    steps:
      #1 Checkout repository code
      - name: Checkout Code
        uses: actions/checkout@v4

      #2 Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.12  # Specify your project's Python version

      #3 Install dependencies
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r appweb/requirements.txt

      #4 Run tests with API key from GitHub Secrets
      - name: Run Tests
        env:
          API_KEY: ${{ secrets.API_KEY }}
        run: |
          pytest --maxfail=5 --disable-warnings
