name: CI/CD Pipeline

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  verify-and-test:
    name: Verify Code and Run Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.12

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r appweb/requirements.txt

      - name: Run Tests
        env:
          API_KEY: ${{ secrets.API_KEY }}
        run: |
          pytest --maxfail=5 --disable-warnings || (echo "Tests failed. Check test_failures.log for details." && pytest --maxfail=5 --disable-warnings > test_failures.log)
      - name: Upload Test Logs (on failure)
        if: failure()
        uses: actions/upload-artifact@v3
        with:
          name: test-failures-log
          path: test_failures.log

  build-and-push:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest
    needs: verify-and-test

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker Image
        run: |
          docker build -t nicwa05/nicwa05_webapp:latest .

      - name: Push Docker Image
        run: |
          docker push nicwa05/nicwa05_webapp:latest

  deploy:
    name: Deploy to Azure Web App
    runs-on: ubuntu-latest
    needs: build-and-push

    steps:
      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: webappnico
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          images: nicwa05/nicwa05_webapp:latest
